# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-02 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=30)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('present_absent', models.BooleanField(default=False)),
                ('img_id', models.CharField(max_length=100)),
            ],
        ),
    ]
