# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-02 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20200802_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='present_absent',
            new_name='is_present',
        ),
        migrations.RenameField(
            model_name='attendence',
            old_name='emp_id',
            new_name='worker',
        ),
    ]
